# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20170612_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('author',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('author',)},
        ),
    ]
